INSERT INTO TBL_USER (NAME ,CTIME) VALUES ('zlikun' ,CURRENT_TIMESTAMP()) ;
INSERT INTO TBL_USER (NAME ,CTIME) VALUES ('kevin' ,CURRENT_TIMESTAMP()) ;
INSERT INTO TBL_USER (NAME ,CTIME) VALUES ('jackson' ,CURRENT_TIMESTAMP()) ;